### ISSUE TITLE
Offer prebuilded for s3

### ISSUE THREAD

**Issue by anondev-sudo** [devtomio/website-screenshot#9]
Create prebuilded version for S3 too (and add option to specify ENDPOINT_URL variable for selfhosted s3 storage). I want to selfhost on railway but their storage isn't persist so the images would be lost.

**Comment by devtomio** [comment]
will work on it

**Comment by devtomio** [comment]
I was able to add support for self-hosted s3 storage, but offering prebuilds for each provider seems too hard for me. And I see that you're using railway, so I've added a [guide](https://github.com/devtomio/website-screenshot#changing-providers) to let users change providers. 

cc @anondev-sudo
